spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/gateway_db
    username: gateway_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090

logging:
  level:
    com.gateway.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
